### ISSUE TITLE
华为推送的token不能返回到flutter端

### ISSUE THREAD

**Issue by zhou-zc** [mofada/flutter_factory_push#1]
`fun getRegistrationId(context: Context, result: MethodChannel.Result) {
        thread {
            try {
                val token = HmsInstanceId.getInstance(context).getToken(null, null)
                result.success(token)
            } catch (e: Exception) {
                e.printStackTrace()
                result.success(null)
            }
        }
    }`
在flutter端不能获取到token

**Comment by mofada** [comment]
华为的token是异步获取的, 不是同步, 需要监听消息才能拿到, 我记得`onPushReceiver<T>`方法有个`onTokenReceiver`回调
[home_page.dart](https://github.com/mofada/flutter_factory_push/blob/master/example/lib/page/home_page.dart)
```
  @override
  void initState() {
    super.initState();

    ///当接收到消息的时候
    ///尽量保证接收消息在初始化前面, 防止token接收不到, 这里为了demo演示, 接收消息放到home
    FactoryPush.onPushReceiver(
        onEvent: (message) => print(message),
        onMessageReceiver: _onEvent,
        onNotificationClicked: _onEvent);
  }

  void _onEvent(PushMessageBean messageBean) {
    _messages.add(messageBean);
    setState(() {});
  }
```

**Comment by mofada** [comment]
这个项目还没有完成, 只适用于学习, 不建议实际开发, 最近在忙其他事情, 没有继续完善插件, 也缺少部分真机测试, 暂时搁置

**Comment by zhou-zc** [comment]
明白了

**Comment by mofada** [comment]
那我关闭问题了
